server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: Kim
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            #이 친구들 Github에 올릴 때는 blur처리 해야함.
            client-id:
            client-secret:
            scope:
              - email
              - profile
          facebook:
            #이 친구들 Github에 올릴 때는 blur처리 해야함.
            client-id:
            client-secret:
            scope:
              - email
              - public_profile
          naver:
            #이 친구들 Github에 올릴 때는 blur처리 해야함.
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8001/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json의 response 키값으로 반환
